# Generated by Django 4.2.1 on 2024-01-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
