# Generated by Django 4.2.1 on 2024-01-09 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 22, 20, 0, 545223, tzinfo=datetime.timezone.utc)),
        ),
    ]
