# Generated by Django 4.2.1 on 2024-01-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cart_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
