# Generated by Django 4.2.1 on 2024-01-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='Asliddin', max_length=255),
        ),
    ]
