# Generated by Django 4.2.1 on 2024-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_likedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_products',
            field=models.ManyToManyField(related_name='liked_users', to='core.product'),
        ),
        migrations.DeleteModel(
            name='LikedProduct',
        ),
    ]
